keygo:
  info:
    title: "@project.parent.name@"
    name: "@project.parent.artifactId@"
    version: "@project.parent.version@"
  bootstrap:
    enabled: true
    admin-key: "${KEYGO_ADMIN_KEY:changeMe}"
    api-path-prefix: "/api/"
    actuator-path-prefix: "/actuator/"
    service-info-path-prefix: "/service/info"
spring:
  application:
    name: "${keygo.info.name}-${keygo.info.version}"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:default}"
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: "${PORT:8080}"
  servlet:
    context-path: "/${keygo.info.name}"
    application-display-name: "${spring.application.name}"
