package io.cmartinezs.keygo.domain.user.model;

import io.cmartinezs.keygo.domain.user.exception.InvalidPasswordException;

/**
 * Utility class for password validation.
 * <p>Clase utilitaria para validación de contraseñas.
 *
 * <p>Sin dependencias externas ni Spring — puro dominio.
 * Valida que una contraseña cumpla los requisitos mínimos de seguridad
 * según su contexto (definitiva o temporaria).
 *
 * @author cmartinezs
 * @version 1.0
 */
public final class PasswordValidationHelper {

  private PasswordValidationHelper() {}

  /**
   * Validates a password according to the security policy.
   * <p>Valida una contraseña de acuerdo a la política de seguridad.
   *
   * @param password the password to validate
   * @param isTemporary {@code true} if the password is temporary (generated by admin);
   *                    {@code false} if it's a permanent password (user-provided)
   * @throws InvalidPasswordException if the password doesn't meet the policy
   */
  public static void validate(String password, boolean isTemporary) {
    if (password == null || password.isBlank()) {
      throw new InvalidPasswordException("password cannot be null or blank");
    }

    if (isTemporary) {
      // Temporary passwords (generated, sent by email) — relaxed minimum
      validateTemporaryPassword(password);
    } else {
      // Permanent passwords (user-defined or admin-set) — strict policy
      validatePermanentPassword(password);
    }
  }

  /**
   * Validates a permanent password (user-provided or admin-set).
   * <p>Valida una contraseña definitiva (proporcionada por usuario o administrador).
   *
   * <p>Reglas:
   * <ul>
   *   <li>Longitud mínima: 12 caracteres</li>
   *   <li>Al menos una letra mayúscula</li>
   *   <li>Al menos una letra minúscula</li>
   *   <li>Al menos un dígito</li>
   *   <li>Al menos un carácter especial (no alfanumérico)</li>
   * </ul>
   *
   * @param password the password to validate
   * @throws InvalidPasswordException if any rule is violated
   */
  static void validatePermanentPassword(String password) {
    if (password.length() < 12) {
      throw new InvalidPasswordException("must be at least 12 characters");
    }
    if (!password.matches(".*[A-Z].*")) {
      throw new InvalidPasswordException("must contain at least one uppercase letter");
    }
    if (!password.matches(".*[a-z].*")) {
      throw new InvalidPasswordException("must contain at least one lowercase letter");
    }
    if (!password.matches(".*\\d.*")) {
      throw new InvalidPasswordException("must contain at least one digit");
    }
    if (!password.matches(".*[^A-Za-z0-9].*")) {
      throw new InvalidPasswordException("must contain at least one special character");
    }
  }

  /**
   * Validates a temporary password (generated by system, sent by email).
   * <p>Valida una contraseña temporaria (generada por el sistema, enviada por email).
   *
   * <p>Reglas (relajadas):
   * <ul>
   *   <li>Longitud mínima: 8 caracteres</li>
   * </ul>
   *
   * <p>Nota: contraseñas temporarias generadas siempre cumplen:
   * mayúscula + minúscula + dígito + especial (generador garantiza esto),
   * por eso no se validan estas reglas aquí.
   *
   * @param password the password to validate
   * @throws InvalidPasswordException if the password is too short
   */
  static void validateTemporaryPassword(String password) {
    if (password.length() < 8) {
      throw new InvalidPasswordException("temporary password must be at least 8 characters");
    }
  }
}

